/*************************************
* Tanner Wagner
*
* This file is used to test the LCG 
* that was implemeted in lcg.c.
* To use it, simply compile it and run
* ./testlcg
*
*************************************/

#include <stdio.h>
#include "lcg.h"

/* Print LCG values along with a message */
/*************************************
* Each parameter’s type and name:
*   - struct LinearCongruentialGenerator* lcg (input): Pointer to a LinearCongruentialGenerator structure representing the LCG.
*   - char* msg (input): Pointer to a string representing a message to be printed alongside the LCG parameters.
* input and/or output,
*   - Output.
* its meaning,
*   - lcg: Pointer to a LinearCongruentialGenerator structure representing the LCG.
*   - msg: Pointer to a string representing a message to be printed.
* its range of values.
*   - lcg: A valid pointer to a LinearCongruentialGenerator structure.
*   - msg: A null-terminated string.
* Function’s return value.
*   - void: This function does not return any value.
* Description of what the function does.
*   - This function prints the parameters of the given Linear Congruential Generator (LCG) along with an additional message.
* Function’s algorithm
*   - Print the additional message (msg) along with the parameters of the LCG (m, a, c, x).
*************************************/

void printLCG(struct LinearCongruentialGenerator* lcg, char* msg)
{
  printf("%s (m=%lu,a=%lu,c=%lu,x=%lu)\n", msg, lcg->m, lcg->a, lcg->c, lcg->x);
}

/* Print message and n values generated by the LCG */
/*************************************
* Each parameter’s type and name:
*   - struct LinearCongruentialGenerator* lcg (input): Pointer to a LinearCongruentialGenerator structure representing the LCG.
*   - char* msg (input): Pointer to a string representing a message to be printed.
*   - int n (input): Number of random values to generate and print.
* input and/or output,
*   - Output.
* its meaning,
*   - lcg: Pointer to a LinearCongruentialGenerator structure representing the LCG.
*   - msg: Pointer to a string representing a message to be printed.
*   - n: Number of random values to generate and print.
* its range of values.
*   - lcg: A valid pointer to a LinearCongruentialGenerator structure.
*   - msg: A null-terminated string.
*   - n: A non-negative integer.
* Function’s return value.
*   - void: This function does not return any value.
* Description of what the function does.
*   - This function generates and prints a specified number of random values using the given Linear Congruential Generator (LCG), along with an additional message.
* Function’s algorithm
*   - Print the additional message (msg).
*   - For each value from 0 to n-1:
*       - Generate the next random value using getNextRandomValue(lcg).
*       - Print the generated random value.
*************************************/

void testValues(struct LinearCongruentialGenerator* lcg, char* msg, int n)
{
  int i;
  printf("%s\n", msg);

  for(i = 0; i < n; ++i)
  {
    unsigned long x = getNextRandomValue(lcg);
    printf("%lu\n", x);
  }
}

/* Create and test a few LCGs */
/*************************************
* Each parameter’s type and name:
*   - None
* input and/or output,
*   - Output
* its meaning,
*   - None
* its range of values.
*   - None
* Function’s return value.
*   - int: Returns 0 upon successful execution.
* Description of what the function does.
*   - This is the main function of the program, which demonstrates the usage of the Linear Congruential Generator (LCG) functions.
* Function’s algorithm
*   - Initialize three LinearCongruentialGenerator structures (lcg1, lcg2, lcg3) with different parameters using makeLCG function.
*   - Initialize three additional LinearCongruentialGenerator structures (lcg4, lcg5, lcg6) with invalid parameters for error testing.
*   - Print the initialized LinearCongruentialGenerator structures using printLCG function.
*   - Perform random value generation tests using the testValues function for lcg1, lcg2, and lcg3.
*   - Print the updated LinearCongruentialGenerator structures after the tests using printLCG function.
*   - Return 0 to indicate successful execution.
*************************************/

int main()
{
  struct LinearCongruentialGenerator lcg1 = makeLCG(126,25);
  struct LinearCongruentialGenerator lcg2 = makeLCG(38875,1234);
  struct LinearCongruentialGenerator lcg3 = makeLCG(4611686018427387904,961168601842738797);

  /* Some error cases */
  struct LinearCongruentialGenerator lcg4 = makeLCG(4,3);
  struct LinearCongruentialGenerator lcg5 = makeLCG(0,5);
  struct LinearCongruentialGenerator lcg6 = makeLCG(5,0);

  
  printLCG(&lcg1, "initialized lcg1");
  printLCG(&lcg2, "initialized lcg2");
  printLCG(&lcg3, "initialized lcg3");

  printLCG(&lcg4, "initialized error test lcg4");
  printLCG(&lcg5, "initialized error test lcg5");
  printLCG(&lcg6, "initialized error test lcg6");
  
  testValues(&lcg1, "test lcg1", 10);
  testValues(&lcg2, "test lcg2", 10);
  testValues(&lcg3, "test lcg3", 10);

  printLCG(&lcg1, "lcg1 after first test");
  printLCG(&lcg2, "lcg2 after first test");
  printLCG(&lcg3, "lcg3 after first test");

  testValues(&lcg1, "test lcg1 again", 20);

  printLCG(&lcg1, "lcg1 after second test");
  
  return 0;
}
